services:
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    networks:
      - kanban_network
    volumes:
      - mongo-data:/data/db

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    restart: always
    env_file:
      - ./backend/.env
    ports:
      - "8001:8001"
    networks:
      - kanban_network
    depends_on:
      - mongo
  
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    restart: always
    ports:
      - "5173:5173"
    networks:
      - kanban_network
    depends_on:
      - backend

networks:
  kanban_network:
    driver: bridge

volumes:
  mongo-data:
    driver: local